public with sharing class MyApexClass01 {
    public MyApexClass01() {
        System.debug('A');        
        if(2 == 2){
            System.debug('dfsdfsdfsfdf');        
        }
        if(2 == 3){
            System.debug('4454554554');        
        }
        System.debug('This is a new apex Classes');
        System.debug('o'); 
        String message2 = 'Gupta';
        String m = 'a'; 
        String a = 'a';
        if(3 ==4){
            System.debug('sdsds');
        }
    }
}
